name: Spree storefront api v2 js sdk - sync

on:
  schedule:
    - cron: '0 4 * * *'  # every day at 4am
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: spree
          base: master
          head: main
          merge_method: merge
          auto_approve: false
